export const ADD_STAFF = 'ADD_STAFF';
export const STAFFS_LOADING = 'STAFFS_LOADING';
export const STAFFS_FAILED = 'STAFFS_FAILED';
export const DELETED_STAFF = 'DELETED_STAFF';

export const ADD_DEPARTMENT = 'ADD_DEPARTMENT';
export const DEPARTMENTS_LOADING = 'DEPARTMENTS_LOADING';
export const DEPARTMENTS_FAILED = 'DEPARTMENTS_FAILED';
export const ADD_DEPARTMENTS = 'ADD_DEPARTMENTS';
